// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230118111714_mig_ananı")]
    partial class mig_ananı
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CommentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CommentUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("ProductID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.GenreCategory", b =>
                {
                    b.Property<int>("GenreCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrlGenreCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameGenreCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.HasKey("GenreCategoryID");

                    b.HasIndex("SubCategoryID");

                    b.ToTable("GenreCategories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.MainCategory", b =>
                {
                    b.Property<int>("MainCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrlMainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameMainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MainCategoryID");

                    b.ToTable("MainCategories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BuyTraderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateProduct")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl1Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl2Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl3Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl4Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl5Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl6Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceProduct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SellTraderID")
                        .HasColumnType("int");

                    b.Property<string>("SizeProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusProduct")
                        .HasColumnType("bit");

                    b.HasKey("ProductID");

                    b.HasIndex("BuyTraderID");

                    b.HasIndex("GenreCategoryID");

                    b.HasIndex("SellTraderID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrlSubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("NameSubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubCategoryID");

                    b.HasIndex("MainCategoryID");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Trader", b =>
                {
                    b.Property<int>("TraderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1Trader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2Trader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3Trader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionTrader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBANTrader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrlTrader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailTrader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumberTrader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraderUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TraderID");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Comment", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.Concrete.GenreCategory", b =>
                {
                    b.HasOne("EntityLayer.Concrete.SubCategory", "SubCategory")
                        .WithMany("GenreCategories")
                        .HasForeignKey("SubCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Product", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Trader", "BuyTrader")
                        .WithMany("TraderBuyer")
                        .HasForeignKey("BuyTraderID");

                    b.HasOne("EntityLayer.Concrete.GenreCategory", "GenreCategory")
                        .WithMany("Products")
                        .HasForeignKey("GenreCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Trader", "SellTrader")
                        .WithMany("TraderSeller")
                        .HasForeignKey("SellTraderID");

                    b.Navigation("BuyTrader");

                    b.Navigation("GenreCategory");

                    b.Navigation("SellTrader");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubCategory", b =>
                {
                    b.HasOne("EntityLayer.Concrete.MainCategory", "MainCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MainCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("EntityLayer.Concrete.GenreCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EntityLayer.Concrete.MainCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Product", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("EntityLayer.Concrete.SubCategory", b =>
                {
                    b.Navigation("GenreCategories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Trader", b =>
                {
                    b.Navigation("TraderBuyer");

                    b.Navigation("TraderSeller");
                });
#pragma warning restore 612, 618
        }
    }
}
